In [1]:
# %%
# ==========================
# Block 1: Load EPC data
# ==========================

import pandas as pd

# Path to processed EPC data
input_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_processed.csv"

df = pd.read_csv(input_path)

df.shape

(136, 118)

In [2]:
# %%
# ==========================
# Block 2: Clean address components
# ==========================

address_cols = ["ADDRESS1", "ADDRESS2", "ADDRESS3", "POSTCODE"]

for col in address_cols:
    df[col] = (
        df[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

df[address_cols].head()

              ADDRESS1 ADDRESS2 ADDRESS3 POSTCODE
0  19 CULCREUCH AVENUE   FINTRY  GLASGOW  G63 0YB
1             GLENVIEW   FINTRY  GLASGOW  G63 0XJ
2  22 CULCREUCH AVENUE   FINTRY  GLASGOW  G63 0YB
3    1 MENZIES TERRACE   FINTRY  GLASGOW  G63 0YJ
4       50 MAIN STREET   FINTRY  GLASGOW  G63 0XF

In [3]:
# %%
# ==========================
# Block 3: Build FullAddress for geocoding
# ==========================

def build_full_address(row):
    parts = [
        row["ADDRESS1"],
        row["ADDRESS2"],
        row["ADDRESS3"],
        row["POSTCODE"],
        "UK"
    ]
    # Keep only non-empty parts
    return ", ".join([p for p in parts if p])

df["FullAddress"] = df.apply(build_full_address, axis=1)

df[["FullAddress"]].head(10)

                                         FullAddress
0  19 CULCREUCH AVENUE, FINTRY, GLASGOW, G63 0YB, UK
1             GLENVIEW, FINTRY, GLASGOW, G63 0XJ, UK
2  22 CULCREUCH AVENUE, FINTRY, GLASGOW, G63 0YB, UK
3    1 MENZIES TERRACE, FINTRY, GLASGOW, G63 0YJ, UK
4       50 MAIN STREET, FINTRY, GLASGOW, G63 0XF, UK
5   18 DUNMORE GARDENS, FINTRY, GLASGOW, G63 0XN, UK
6  11 CULCREUCH AVENUE, FINTRY, GLASGOW, G63 0YB, UK
7       19 MAIN STREET, FINTRY, GLASGOW, G63 0XA, UK
8    6 MENZIES TERRACE, FINTRY, GLASGOW, G63 0YJ, UK
9   Cul a Mhuilinn, Kippen Road, Fintry, G63 0YD, UK

In [4]:
# %%
# ==========================
# Block 4: Save fintry_addresses.csv
# ==========================

output_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_addresses.csv"

address_df = df[["FullAddress"]].drop_duplicates().reset_index(drop=True)

address_df.to_csv(output_path, index=False)

output_path, address_df.shape

('/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_addresses.csv',
 (136, 1))

In [5]:
# %%
# ==========================
# Block 5: Sanity checks
# ==========================

address_df.sample(10)

                                           FullAddress
50   CULCREUCH NORTH LODGE, FINTRY, GLASGOW, G63 0L...
4         50 MAIN STREET, FINTRY, GLASGOW, G63 0XF, UK
127          Tynlone Cottage, Fintry Road, G63 0RR, UK
12        47 MAIN STREET, FINTRY, GLASGOW, G63 0XE, UK
102     CRAIGTON COTTAGE, FINTRY, GLASGOW, G63 0XQ, UK
108         WHITE GABLES, FINTRY, GLASGOW, G63 0YH, UK
41      7 MENZIES AVENUE, FINTRY, GLASGOW, G63 0YE, UK
47                BRUACH, FINTRY, GLASGOW, G63 0YH, UK
103      2 MENZIES DRIVE, FINTRY, GLASGOW, G63 0YG, UK
9     Cul a Mhuilinn, Kippen Road, Fintry, G63 0YD, UK