# Step 1: Overview — Script Description
# ------------------------------------
# This script processes an EPC dataset and assigns lifetime values for building fabric elements
# (walls, windows, roof, and overall fabric) based on predefined upgrade types.
#
# INPUT:
# - CSV file containing upgrade type columns:
#   WALLS_UPGRADE_TYPE, WINDOWS_UPGRADE_TYPE, ROOF_UPGRADE_TYPE
#
# OUTPUT:
# - Updated CSV file with new/updated columns:
#   WALLS_LIFETIME, WINDOWS_LIFETIME, ROOF_LIFETIME, FAB_LIFETIME
#
# LOGIC:
# - WALLS_LIFETIME is assigned based on WALLS_UPGRADE_TYPE mapping
# - WINDOWS_LIFETIME is assigned based on WINDOWS_UPGRADE_TYPE mapping
# - ROOF_LIFETIME is assigned based on ROOF_UPGRADE_TYPE mapping
# - FAB_LIFETIME is set to a constant value (50 years) for all rows
#
# NOTES:
# - Any upgrade types not found in the mapping will result in NaN values
# - Ensure column names match exactly (case-sensitive)

In [1]:
# Step 2: Import Libraries
# -----------------------
import pandas as pd

In [2]:
# Step 3: Load Dataset
# -------------------
file_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_with_costs_2.csv"
df = pd.read_csv(file_path)

# Preview dataset
df.head()

,BUILDING_REFERENCE_NUMBER,OSG_REFERENCE_NUMBER,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,LATITUDE,LONGITUDE,ORIENTATION,ORIENTATION_ESPR_ROT,...,BATTERY_NPV_FLEX,WINDOWS_IRR_FLEX,ROOF_IRR_FLEX,WALLS_IRR_FLEX,FAB_IRR_FLEX,HP_IRR_FLEX,SOLAR_THERMAL_IRR_FLEX,PV_IRR_FLEX,BATTERY_IRR_FLEX,PEAK_HP_LOAD
0,1001829067,122009933.0,19 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.0557,-4.2233,100,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,977.038423
1,1001951858,122010025.0,GLENVIEW,FINTRY,GLASGOW,G63 0XJ,56.0528,-4.2206,180,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2363.181338
2,1001829071,122009868.0,22 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.0555,-4.2237,100,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540.540497
3,1234761001,122009968.0,1 MENZIES TERRACE,FINTRY,GLASGOW,G63 0YJ,56.0584,-4.2248,150,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1431.249048
4,1001991633,122009892.0,50 MAIN STREET,FINTRY,GLASGOW,G63 0XF,56.0547,-4.2283,150,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473.933683

In [3]:
# Step 4: Define Lifetime Mappings
# --------------------------------

# Walls lifetime mapping
walls_lifetime_map = {
    "none": 0,
    "external": 50,
    "external_and_cavity": 30,
    "cavity": 30,
    "internal": 80
}

# Windows lifetime mapping
windows_lifetime_map = {
    "uPVC": 35
}

# Roof lifetime mapping
roof_lifetime_map = {
    "loft": 80,
    "rafters": 80
}

In [4]:
# Step 5: Apply Lifetime Mappings
# ------------------------------

# Assign lifetimes based on upgrade type
df["WALLS_LIFETIME"] = df["WALLS_UPGRADE_TYPE"].map(walls_lifetime_map)
df["WINDOWS_LIFETIME"] = df["WINDOWS_UPGRADE_TYPE"].map(windows_lifetime_map)
df["ROOF_LIFETIME"] = df["ROOF_UPGRADE_TYPE"].map(roof_lifetime_map)

In [5]:
# Step 6: Assign FAB_LIFETIME (Constant)
# -------------------------------------
df["FAB_LIFETIME"] = 50

In [6]:
# Step 7: Validate Results
# -----------------------
# Check for missing values (unmapped categories)
print("Missing WALLS_LIFETIME values:", df["WALLS_LIFETIME"].isna().sum())
print("Missing WINDOWS_LIFETIME values:", df["WINDOWS_LIFETIME"].isna().sum())
print("Missing ROOF_LIFETIME values:", df["ROOF_LIFETIME"].isna().sum())

# Preview updated dataframe
df.head()

Missing WALLS_LIFETIME values: 0
Missing WINDOWS_LIFETIME values: 0
Missing ROOF_LIFETIME values: 0

,BUILDING_REFERENCE_NUMBER,OSG_REFERENCE_NUMBER,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,LATITUDE,LONGITUDE,ORIENTATION,ORIENTATION_ESPR_ROT,...,BATTERY_NPV_FLEX,WINDOWS_IRR_FLEX,ROOF_IRR_FLEX,WALLS_IRR_FLEX,FAB_IRR_FLEX,HP_IRR_FLEX,SOLAR_THERMAL_IRR_FLEX,PV_IRR_FLEX,BATTERY_IRR_FLEX,PEAK_HP_LOAD
0,1001829067,122009933.0,19 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.0557,-4.2233,100,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,977.038423
1,1001951858,122010025.0,GLENVIEW,FINTRY,GLASGOW,G63 0XJ,56.0528,-4.2206,180,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2363.181338
2,1001829071,122009868.0,22 CULCREUCH AVENUE,FINTRY,GLASGOW,G63 0YB,56.0555,-4.2237,100,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540.540497
3,1234761001,122009968.0,1 MENZIES TERRACE,FINTRY,GLASGOW,G63 0YJ,56.0584,-4.2248,150,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1431.249048
4,1001991633,122009892.0,50 MAIN STREET,FINTRY,GLASGOW,G63 0XF,56.0547,-4.2283,150,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473.933683

In [7]:
# Step 8: Save Output File
# -----------------------
output_path = "/Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_with_lifetimes_2.csv"
df.to_csv(output_path, index=False)

print(f"File successfully saved to: {output_path}")

File successfully saved to: /Users/jakegehrung/Desktop/data_raw/data_processed/fintry_epc_with_lifetimes_2.csv